import { eventOccursOnDate } from '../src/dates';
import { CalendarEvent } from '../src/types';

type eventOccursOnDateTestCase = {
  name: string,
  date: string,
  event: CalendarEvent,
  expectedBool: boolean
};

const eventOccursOnDateTestCases: eventOccursOnDateTestCase[] = [
  {
    name: 'A null date should return false',
    date: null,
    event: {
      name: 'event',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [],
        weeks: [],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: false,
  },
  {
    name: 'An undefined date should return false',
    date: undefined,
    event: {
      name: 'event',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [],
        weeks: [],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: false,
  },
  {
    name: 'An event that happens on January 21st should be listed as occurring on that day',
    date: '20230121',
    event: {
      name: 'event',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [0],
        day: 21,
        daysOfWeek: [],
        weeks: [],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on December 3rd should be listed as occurring on that day',
    date: '20231203',
    event: {
      name: 'event',
      description: undefined,
      calendar: 'something',
      occurrenceInfo: {
        time: undefined,
        months: [11],
        day: 3,
        daysOfWeek: [],
        weeks: [],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on the 3rd Sunday of June should be listed as happening on June 18, 2023',
    date: '20230618',
    event: {
      name: 'event',
      description: undefined,
      calendar: 'something',
      occurrenceInfo: {
        time: undefined,
        months: [5],
        day: 0,
        daysOfWeek: [0],
        weeks: [3],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on the 2nd Saturday of any month should be listed as happening on November 11, 2023',
    date: '20231111',
    event: {
      name: 'event',
      description: undefined,
      calendar: 'something',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [6],
        weeks: [2],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on Monday should not be listed as happening on a day that is a Tuesday',
    date: '20231107',
    event: {
      name: 'event',
      description: undefined,
      calendar: 'something',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [1],
        weeks: [],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: false,
  },
  {
    name: 'An event that happens on Monday should be listed as happening on a day that is a Monday',
    date: '20231106',
    event: {
      name: 'event',
      description: undefined,
      calendar: 'something',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [1],
        weeks: [],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on Easter should be listed as happening on April 9, 2023',
    date: '20230409',
    event: {
      name: 'Easter',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [],
        weeks: [],
        isEaster: true,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on Easter should be listed as happening on April 17, 2022',
    date: '20220417',
    event: {
      name: 'Easter',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [],
        weeks: [],
        isEaster: true,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on Good Friday should be listed as happening on April 7, 2023',
    date: '20230407',
    event: {
      name: 'Good Friday',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [],
        weeks: [],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: true,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on Good Friday should be listed as happening on April 15, 2022',
    date: '20220415',
    event: {
      name: 'Good Friday',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [],
        weeks: [],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: true,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on Palm Sunday should be listed as happening on April 2, 2023',
    date: '20230402',
    event: {
      name: 'Palm Sunday',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [],
        weeks: [],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: true,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on Palm Sunday should be listed as happening on April 10, 2022',
    date: '20220410',
    event: {
      name: 'Palm Sunday',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [],
        weeks: [],
        isEaster: false,
        isElectionDay: false,
        isGoodFriday: false,
        isPalmSunday: true,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on Election Day should be listed as happening on November 7, 2023',
    date: '20231107',
    event: {
      name: 'Election Day',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [],
        weeks: [],
        isEaster: false,
        isElectionDay: true,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
  {
    name: 'An event that happens on Election Day should be listed as happening on November 5, 2024',
    date: '20241105',
    event: {
      name: 'Election Day',
      description: undefined,
      calendar: 'holidays',
      occurrenceInfo: {
        time: undefined,
        months: [],
        day: 0,
        daysOfWeek: [],
        weeks: [],
        isEaster: false,
        isElectionDay: true,
        isGoodFriday: false,
        isPalmSunday: false,
      },
    },
    expectedBool: true,
  },
];

describe('Event Occurs on Date', () => {
  for (const testCase of eventOccursOnDateTestCases) {
    it(testCase.name, () => {
      const actual = eventOccursOnDate(testCase.date, testCase.event);

      expect(actual).toEqual(testCase.expectedBool);
    });
  }
});
